#!/usr/bin/env python3
"""
    Description: Import async_generator from the last task and 
    create a coroutine called async_comprehension with no arguments.
    The coroutine collects 10 random numbers using async 
    comprehension over async_generator and returns them.

"""
from typing import List
from importlib import import_module as using


async_generator = using('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """"" Return list of values generated by async_generator. """
    return [num async for num in async_generator()]
